spring.application.name=bff

server.port=8080

# URLs de Azure Functions
azure.functions.estudiantes.crud.url=https://biblioteca-cn2-axcrbra7gqgtgrgc.eastus2-01.azurewebsites.net/api/estudiantes
azure.functions.libros.crud.url=https://biblioteca-cn2-axcrbra7gqgtgrgc.eastus2-01.azurewebsites.net/api/libros
azure.functions.prestamos.crud.url=https://biblioteca-cn2-axcrbra7gqgtgrgc.eastus2-01.azurewebsites.net/api/prestamos

azure.functions.rest.estudiantes.url=https://biblioteca-cn2-axcrbra7gqgtgrgc.eastus2-01.azurewebsites.net/api/rest/estudiantes
azure.functions.rest.libros.url=https://biblioteca-cn2-axcrbra7gqgtgrgc.eastus2-01.azurewebsites.net/api/rest/libros

azure.functions.graphql.libros.url=https://biblioteca-cn2-axcrbra7gqgtgrgc.eastus2-01.azurewebsites.net/api/graphql/libros
azure.functions.graphql.prestamos.url=https://biblioteca-cn2-axcrbra7gqgtgrgc.eastus2-01.azurewebsites.net/api/graphql/prestamos