spring.application.name=bff

server.port=8080

# URLs de las funciones Serverless en AWS
aws.lambda.libros.url=https://si6ye7rgi6ln4xsdzgu7vywc5u0fnugg.lambda-url.us-east-1.on.aws/
aws.lambda.estudiantes.url=https://gubdzoimmxs2344pfkmpb2mgiu0wttzr.lambda-url.us-east-1.on.aws/
aws.lambda.prestamos.url=https://7dikd5lykrh3xofjfj7gptfkyy0csgxq.lambda-url.us-east-1.on.aws/